# Copyright (c) 2026 Prawin Kumar

"""
===============================================================================
  PYTHON FOR AI -- Lesson 33: Chunking Strategies & Vector Embeddings
  Difficulty: Intermediate
===============================================================================

  What you will learn:
    - The core concept of RAG (Retrieval-Augmented Generation)
    - Why we chunk large files: Context windows and semantic relevance
    - Recursive Character Splitting and Chunk Overlap mechanics
    - What is a Vector Embedding? (Text converted to geometric coordinates)
    - Calculating Cosine Similarity (Semantic Closeness) in pure Python math

  Why this matters for AI:
    You cannot send a 200-page company manual as prompt context to an LLM every time.
    It is slow, expensive, and fails. Instead, you must slice the manual into
    500-word chunks, convert them to vector embeddings, search for the 3 chunks
    most semantically similar to the user's query, and send only those 3 chunks
    as context! This is the foundation of RAG.

  Estimated time: 20 minutes

===============================================================================
"""

import math

# === WHAT ARE VECTOR EMBEDDINGS? ============================================
#
# WHAT IS AN EMBEDDING AND A VECTOR?
#   - A Vector is simply a long list of numbers representing coordinates (like a GPS coordinate, but instead
#     of just 2 numbers for Latitude/Longitude, a vector might have 1,536 dimensions!).
#   - An Embedding is the vector coordinate that a specialized model generates to represent the MEANING of
#     a piece of text. Think of it like taking a word and finding its exact coordinate position on a giant
#     "galaxy map" of human language. Words that mean similar things are placed on neighboring planets,
#     while completely different words are in entirely separate solar systems!
#
# A vector embedding is a list of floating-point numbers (an array) generated by
# a specialized model (like OpenAI's text-embedding-ada-002).
#
# The Magic of Embeddings:
#   - Semantic meaning is converted to geometric coordinates.
#   - Words with similar meanings (e.g. "king" and "queen") are positioned close
#     to each other in high-dimensional space.
#   - Words with different meanings (e.g. "apple" and "database") are far apart.

# print("--- 1. SEMANTIC GEOMETRIC COORDINATES ---")
# If we have 2D embeddings (for visualization):
print("  Vector 'Python Coding'  = [0.9, 0.1]")
print("  Vector 'Software Dev'   = [0.85, 0.15]  <-- Very close geometrically!")
print("  Vector 'Delicious Cake' = [0.05, 0.95]  <-- Far away!")


# === CHUNKING STRATEGIES & OVERLAP ==========================================
#
# WHAT IS CHUNKING AND SEMANTIC SIMILARITY?
#   - Chunking is the process of slicing a long book or document into smaller, bite-sized paragraphs (chunks).
#     This ensures the text fits into the AI's short-term memory (context window) and prevents important facts
#     from getting lost in a sea of words.
#     (Context Window explained in Module 2, Lesson 4 — "Context-Driven AI")
#   - Semantic Similarity is a measure of how close two concepts are in meaning, regardless of whether they
#     use the exact same words. For example, "feline companion" and "pet cat" have high semantic similarity
#     even though they share zero letters!
#
# Slicing documents into chunks is a balancing act:
#   - If chunks are too small (e.g. 10 characters), they lose context.
#   - If chunks are too large (e.g. 50,000 characters), they dilute the meaning.
#
# Chunk Overlap:
#   We keep a small overlap (e.g. 10-20%) between consecutive chunks. This ensures
#   that a sentence cut in half at a boundary is preserved in full in the adjacent chunk.

# print("\n--- 2. CHUNKING WITH OVERLAP WINDOW ---")

def simulate_character_chunking(text, chunk_size=60, chunk_overlap=15):
    chunks = []
    start = 0
    
    while start < len(text):
        end = min(start + chunk_size, len(text))
        chunk = text[start:end]
        chunks.append((start, end, chunk))
        
        # Shift start forward by chunk_size minus overlap
        # This creates the overlapping window!
        start += (chunk_size - chunk_overlap)
        
        # Safety break if we aren't moving forward
        if chunk_size <= chunk_overlap:
            break
            
    return chunks

sample_manual = (
    "Retrieval-Augmented Generation (RAG) is a technique that grounds "
    "large language models on private datasets. It prevents hallucinations "
    "by supplying real document snippets as prompts context."
)

manual_chunks = simulate_character_chunking(sample_manual, chunk_size=80, chunk_overlap=20)
print(f"Original Text Length: {len(sample_manual)} characters.")
print(f"Generated {len(manual_chunks)} overlapping chunks:")
for idx, (s, e, text_val) in enumerate(manual_chunks, start=1):
    print(f"  Chunk #{idx} (Char {s}-{e}): '{text_val}'")


# === MATHEMATICAL COSINE SIMILARITY IN PYTHON ================================
#
# WHAT IS COSINE SIMILARITY?
#   Cosine Similarity is the mathematical tool we use to measure how close two vector coordinates are
#   on our language galaxy map. Instead of measuring the straight-line distance, it measures the ANGLE
#   between the two coordinate lines pointing from the center of the map. If the angle is 0 degrees, the
#   cosine is 1.0, meaning the two text snippets point in the exact same direction and share the same meaning!
#
# How do we measure the closeness of two vectors? We calculate the cosine of the
# angle between them.
#   - Cosine Similarity = 1.0  -> Vectors point in the exact same direction (Identical meaning).
#   - Cosine Similarity = 0.0  -> Vectors are orthogonal (No relationship).
#   - Cosine Similarity = -1.0 -> Vectors point in opposite directions.
#
# Formula: (A • B) / (||A|| * ||B||)
#   Where A • B is the dot product, and ||A|| is the magnitude.

# print("\n--- 3. CALCULATING SEMANTIC SIMILARITY ---")

def dot_product(v1, v2):
    return sum(x * y for x, y in zip(v1, v2))

def magnitude(v):
    return math.sqrt(sum(x * x for x in v))

def cosine_similarity(v1, v2):
    mag1 = magnitude(v1)
    mag2 = magnitude(v2)
    if mag1 == 0 or mag2 == 0:
        return 0.0
    return dot_product(v1, v2) / (mag1 * mag2)

# Let's define mock embeddings for three prompts:
#   v_query   = "How do I build a backend API in Python?"
#   v_target1 = "FastAPI is a modern web framework for Python routers."
#   v_target2 = "Making homemade apple pie requires baking apples and flour."

v_query   = [0.90, 0.85, 0.05]
v_target1 = [0.88, 0.82, 0.08] # Semantically close to query (high first/second coords)
v_target2 = [0.02, 0.10, 0.95] # Semantically unrelated to query (high third coord)

sim_api = cosine_similarity(v_query, v_target1)
sim_pie = cosine_similarity(v_query, v_target2)

print(f"Cosine Similarity (Query vs FastAPI Tech Doc): {sim_api:.4f} (Highly Relevant!)")
print(f"Cosine Similarity (Query vs Apple Pie Recipe):  {sim_pie:.4f} (Unrelated)")


# === RETRIEVAL SEGMENT OVERFLOW =================─────────────────────────────
#
# A complete RAG loop looks like this:
#   1. User Query ──► Generate Embeddings
#   2. Match embeddings against all indexed document chunks in DB using Cosine Similarity
#   3. Retrieve Top-K matches (e.g. Top 3 matching text chunks)
#   4. Format Context: "Answer the query based on these facts: [Matches]"
#   5. Query LLM and return output!

# print("\n--- 4. THE COMPLETE RAG PIPELINE MAP ---")
print("  Query ──► Vector Similarity Search ──► Top-K context injection ──► Grounded LLM Response")


# === COMMON MISTAKES ==========================================================

# MISTAKE 1: Naive character-count splitting cutting words in half
#   If you split strictly every 500 characters, you will split words (like "FastAPI"
#   becoming "Fast" in chunk 1 and "API" in chunk 2).
#   Use Recursive Character splitting which splits by double newlines (`\n\n`),
#   single newlines (`\n`), spaces (` `), and finally individual characters.

# MISTAKE 2: Storing embeddings as raw text arrays in standard databases
#   Running Cosine Similarity queries across millions of rows in a traditional SQL
#   database is incredibly slow. Always use dedicated Vector Databases (like ChromaDB,
#   Pinecone, or pgvector) that utilize HNSW indexing for millisecond lookups.

# MISTAKE 3: Neglecting chunk overlap context
#   Without overlap, boundary pronouns (e.g., "It resolves conflicts.") are separated
#   from their noun subjects ("Git") in preceding chunks, causing retrieval errors.
#   Always keep a 10% to 20% overlap window.


# === EXERCISES ================================================================
#
# Exercise 1: Build a simple Paragraph-level chunker `split_by_paragraph(text)`
#             that splits a document by `\n\n` separators and filters out empty chunks.
#
# Exercise 2: Calculate the cosine similarity between vector [1.0, 0.0] and [0.0, 1.0].
#             Explain the geometric result.

# === SOLUTIONS ================================================================
#
# Exercise 1:
# def split_by_paragraph(text):
#     return [p.strip() for p in text.split("\n\n") if p.strip()]
#
# Exercise 2:
# # Cosine similarity = 0.0. Geometric result: The vectors are perfectly perpendicular,
# # indicating complete semantic divergence (no shared meaning).


# === KEY TAKEAWAYS ============================================================
#
# - Vector embeddings translate semantic concepts into searchable geometric metrics.
# - RAG prevents LLM hallucinations by supplying retrieved documents as evidence.
# - Chunking slices large files to fit prompt limits and concentrate search accuracy.
# - Overlap windows ensure continuous context flows across adjacent chunk divisions.
# - Cosine Similarity mathematically isolates relevant evidence from unrelated noise.
